language: python
python:
  - 2.7
  - 3.4
  - 3.5
services:
  - postgresql
addons:
  postgresql: "9.4"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install coveralls
script:
  - coverage run --append runtests.py -U postgres -w
after_success:
  coveralls
